### ISSUE TITLE
Drogensystem - Inventar duplizierung

### ISSUE THREAD

**Issue by NixMuss** [nSystemz/nemesus-world-server#10]
Man kann seine Drogen duplizieren,  indem man einmal aufsammelt und das nächste unendlich kriegen kann.
Ich versuche selbst sowas zu fixen aber ich komme nicht mehr weiter.

**Comment by nSystemz** [comment]
Hi, was meinst du denn mit `und das nächste unendlich kriegen kann`?

**Comment by NixMuss** [comment]
Bei der nächste Pflanze kann man sich unendlich Koks oder Marihuana erfarmen, egal ob der Inventar voll ist oder nicht.

**Comment by nSystemz** [comment]
Danke, Fehler wurde behoben.
