### ISSUE TITLE
Discord Bug

### ISSUE THREAD

**Issue by MaxiWaynee** [nSystemz/nemesus-world-server#11]
Im discord wird immer noch beim Bot angezeigt das angeblich 2 spieler drauf sind obwohl ich alles richtig eingetragen habe anscheinend reagiert der bot nicht mal drauf wie viel personen online sind

**Comment by nSystemz** [comment]
Der Bot wurde nicht zu ende entwickelt, das müsste man selber machen. Sofern man einen Discord Bot benötigt.
