### ISSUE TITLE
Fuel Bug

### ISSUE THREAD

**Issue by MichaelWarzwq** [nSystemz/nemesus-world-server#13]
Hello, if my fuel is at 0% in the speedometer, the vehicle can still drive, even with vehicle damage if it is at 0%, it can still drive and in the f2 menu under vehicles there are always other data than in the speedometer

**Comment by JensGamerBoy** [comment]
So for me it doesn't bug around because from 25% the car is already on fire

**Comment by nSystemz** [comment]
S. andere Fehlermeldung, Workaround für das Fahrzeugzerstörungssystem mit mit dem nächsten Update, Fuelsystem wurde bereits aktualisiert.
