### ISSUE TITLE
Kein Crosshair in der Shooting Range

### ISSUE THREAD

**Issue by DomePlaysHD** [nSystemz/nemesus-world-server#14]
Wenn man die praktische Waffenscheinprüfung macht wird kein HUD & Crosshair angezeigt.

**Comment by nSystemz** [comment]
Danke für die Meldung, beim normalen Waffenschein ist das gewollt (soll ja nicht so einfach sein). Bei der normalen Shooting Range hat man demnächst wieder ein Crosshair.
