### ISSUE TITLE
Handy Buggy

### ISSUE THREAD

**Issue by jxcsx** [nSystemz/nemesus-world-server#15]
Ich kann nur den ersten Kontakt auswählen, alle weiteren kontakte kann man nicht anrufen und wenn man den chat öffnet landet man im chat vom ersten Kontakt-

**Comment by maymatxacamtay** [comment]
Ich erhalte auch die Fehlermeldung error 017: undefined symbol "dest"

**Comment by maymatxacamtay** [comment]
NemesusRoleplay.pwn(196517) : warning 208: function with tag result used before definition, forcing reparse
NemesusRoleplay.pwn(96045) : error 017: undefined symbol "dest"
NemesusRoleplay.pwn(96048) : error 017: undefined symbol "dest"
NemesusRoleplay.pwn(96048) : warning 215: expression has no effect
NemesusRoleplay.pwn(96048) : error 001: expected token: ";", but found "]"
NemesusRoleplay.pwn(96048) : error 029: invalid expression, assumed zero
NemesusRoleplay.pwn(96048) : fatal error 107: too many error messages on one line

**Comment by nSystemz** [comment]
Hi, Fehler wurde behoben.
