### ISSUE TITLE
Vorschläge für Server erweiterung

### ISSUE THREAD

**Issue by DuleM85** [nSystemz/nemesus-world-server#16]
Einen Business erstellen, vielleicht kennst es schon oder mal was davon gehört. CheapCarDealerShip.
Kurze beschreibung:
Man kauft das Business, danach hat man möglichkeit einen gebrauchten Wagen von anderen Spieler zu kaufen und es dann in den Business reinstellen. z.B. Man sitzt in das Fahrzeug, gibt dann /carprice [Preis] und das Auto ist dann als Gebrauchtwagen zum verkauf verfügbar. Natürlich sollte Datenbank vorhanden sein. Das Geld vom verkauften Auto sollte mit der selbst erstellten Gruppe in der Stadthalle auf dem Firmenkonto raufkommen..

Das wäre ein gutes RP Business.. Man könnte das Fahrzeug mit hilfe von den Skirpt verkaufen aber auch Selber an Ort und Stelle. Der Business besitzer soll auch die möglichkeit haben das Fahrzeug aus dem Business rausnehmen zu können mit z.B. dem Komando /carprice [Preis 0/NULL].

Dieses System habe ich bei einen anderen Server gesehen und auch als Business betrieben und ist sehr interessantes Business....

**Comment by nSystemz** [comment]
Danke für deinen Vorschlag, ich notiere mir den mal für die Zukunft. Erstmal werde ich das aber als Issue schließen. Vorschläge zukünftig bitte via Discord schreiben. Danke!
