### ISSUE TITLE
Fehler bei der Blutanzeige

### ISSUE THREAD

**Issue by LiMaKen** [nSystemz/nemesus-world-server#19]
Wenn ich mich beim Server anmelde und einem Spieler in der Nähe begegne, dessen Gesundheit 11 % beträgt, springt sie automatisch auf 100 % und wieder zurück auf 11 %. Das passiert immer und immer wieder.
[https://imgur.com/vihaR1C](url)

**Comment by nSystemz** [comment]
Wurde angepasst, danke für die Meldung.
