### ISSUE TITLE
Türen Bug

### ISSUE THREAD

**Issue by MaxiWaynee** [nSystemz/nemesus-world-server#2]
Wenn man einer Haustür mit /chd ein hash gegeben hat von der richtigen tür und die richtige hausnummer einträgt dann kann man als Admin im Dienst die tür öffnen aber als Hausbesitzer bzw schlüsselbesitzer nicht genauso beim befehl /chd sagt er immer ungültige hausid wahrscheinlich weil da irgendwas mit Business abgefragt wird

**Comment by nSystemz** [comment]
Fehler wurde mit dem letzten Commit behoben, s. Helper.cs.
