### ISSUE TITLE
Craften

### ISSUE THREAD

**Issue by MaxiWaynee** [nSystemz/nemesus-world-server#21]
wenn ich space Cookies Crafte beim 1x craften macht er die animation und es wird wie gewollt alles abgezogen aber wenn ich dann weiter die cookies crafte wird nix mehr abgezogen und keine animation wird gemacht bekomme aber trozdem immer +10 cookies

Der fehler kommt dann 

[OnCraftItem]: System.NullReferenceException: Object reference not set to an instance of an object.
   at void NemesusWorld.Controllers.GangController.OnCraftItem(Player player, string craftsettings)

**Comment by nSystemz** [comment]
Aktuell gibt es kein Problem mit dem Crafting, das Herstellen der Cookies funktioniert auch wie gewohnt. Da die Fehlermeldung schon etwas älter ist, kann es sein das ein älteres Update diesen Fehler behoben hat.
