### ISSUE TITLE
Möbelversteck

### ISSUE THREAD

**Issue by MaxiWaynee** [nSystemz/nemesus-world-server#22]
Ich habe meine sachen in ein möbelversteck gepackt nach dem server restart waren die möbel leer und meine sachen weg

**Comment by nSystemz** [comment]
Vor dem Restart, Server gespeichert?

**Comment by MaxiWaynee** [comment]
ne habe gedacht der macht das automatisch

**Comment by nSystemz** [comment]
Ich füge eine Speicherung der Furnitures zur Speicherungs Funktion hinzu, trotzdem empfehle ich auch z.B ein automatisiertes /saveall vor Restart.
