### ISSUE TITLE
Sammel und Verarbeitung / Produktion Script - und - Fahrzeug Bauen

### ISSUE THREAD

**Issue by BLACKWOLF0401** [nSystemz/nemesus-world-server#23]
hallo wäre es möglich für nächsten update Produktion Script zu machen für Sammeln und weiter Verarbeitungen sowie auch verkaufen.

und was ich cool finden würde wenn man mit verschieden item wie aus Metalle Fahrzeuge bauen könnte

**Comment by nSystemz** [comment]
In diesem GM haben wir uns extra gegen Sammeln/Verarbeiten und dem ganzen Standard Prinzip entschieden um mal was neues zu machen. So ein System müsstest du selber integrieren, wenn du dabei Hilfe benötigst melde dich gerne im Discord.
