### ISSUE TITLE
Vorschlag zum Spawnsystem

### ISSUE THREAD

**Issue by DrDownloader** [nSystemz/nemesus-world-server#26]
Guten Tag,
Ich hätte gerne ein System eingebaut wo man wenn man sich einloggt auswählen kann wo man spawnen will also in seiner Fraktions BASE/HQ oder im Haus oder am letzten Standort.

Alternativ per F2 änderbar und dort spawnt man dann immer.

Je nach dem was du machen willst aber bitte eins von beidem.

**Comment by nSystemz** [comment]
Eine Anpassung global wird es erstmal nicht geben, da der Quellcode "offen" ist kann du diese ja gerne für dich vornehmen.
