### ISSUE TITLE
GOV System

### ISSUE THREAD

**Issue by DrDownloader** [nSystemz/nemesus-world-server#27]
Guten Morgen,
Ich hätte gerne ein /gov Command wo die Regierung eine Nachricht an alle Spieler in den Chat schicken kann.

Dort soll dann drin stehen welcher Rank und Welche Person + Nachricht.

**Comment by JensGamerBoy** [comment]
Naja aber da es eig für VoiceRP ist müsstest du dir das selber einbauen finde ich :D

**Comment by Crafti1995** [comment]
Der GOV Command existiert indirekt bereits, man kann über das MDC eine Staatsnachricht versenden welche dann jeder Spieler aufs Handy bekommt.

**Comment by nSystemz** [comment]
Über das MDC kannst du eine Staatsankündigung schreiben.
