### ISSUE TITLE
BUG Wetter

### ISSUE THREAD

**Issue by DrDownloader** [nSystemz/nemesus-world-server#28]
Ich musste alle Wetter Funktionen entfernen da ich sonst ein 404 oder 500 oder 505 bekam.
Also ingame ist es auch immer nachts dauerhaft.

Bitte fixxen.

**Comment by nSystemz** [comment]
Bitte stelle sicher das dein Server folgende URL aufrufen kann: https://nemesus-world.de/WetterInfo.php

**Comment by nSystemz** [comment]
Das Wettersystem wurde aktualisiert.
