### ISSUE TITLE
Komplettes Kaputtes Auto Bug

### ISSUE THREAD

**Issue by MaxiWaynee** [nSystemz/nemesus-world-server#3]
Wenn das auto komplett kaputt ist kann der Spieler es nicht mehr wieder bekommen ACLS kann es auch nicht reparieren man kann es nur noch wieder holen wenn man den server restartet

**Comment by nSystemz** [comment]
Danke für deine MEldung, im nächsten Update werde ich einen Workaround dafür erstellen.
