### ISSUE TITLE
Kofferraum Lagerplatzanzeige

### ISSUE THREAD

**Issue by BOC0815** [nSystemz/nemesus-world-server#34]
Der Kofferraum hat keine Begrenzung, der Balken zur anzeige des Gewichts funktioniert nicht.

**Comment by nSystemz** [comment]
![grafik](https://github.com/user-attachments/assets/a4697682-f0f2-4c9e-8393-f5f890aad2a5)

Die Anzeige wurde auch in einem der letzten Updates behoben.
