### ISSUE TITLE
ACLS öl Nachfüllen bug

### ISSUE THREAD

**Issue by MaxiWaynee** [nSystemz/nemesus-world-server#4]
Wenn man als ACLS öl nachfüllen will tritt folgende Errormeldung auf 
![e7c33c2b7a1bdea211d2bf309baeac5e](https://github.com/nSystemz/nemesus-world-server/assets/59547286/e5c4dc2c-5c06-405a-b2fd-c0cb6aee1768)

**Comment by nSystemz** [comment]
`let closestVeh = getClosestVehicle(localPlayer.position);`
+ Überprüfung ob das Fahrzeug gefunden wurde im Clientseitigen Code.

Oder die Korrektur aus dem letzten Commit nehmen.
