### ISSUE TITLE
Hud Bug

### ISSUE THREAD

**Issue by NixMuss** [nSystemz/nemesus-world-server#5]
Keine Ahnung wie man das auslöst, sobald man in einem Auto einsteigt, verschwindet das Hud, wenn man rausgeht kommt das wieder aber halt 0 kmh anzeige usw.

**Comment by MaxiWaynee** [comment]
Hat was mit dem Funkgerät zu tun wen man es im Fahrzeug einschaltet dann verschwindet das Hud macht man es wieder im Fahrzeug aus ist das Hud wieder da

**Comment by nSystemz** [comment]
Mit dem nächsten Update wird das Speedo wieder angezeigt, sofern man das Menü von Funkgerät verlässt.
