### ISSUE TITLE
Tötungs Bug

### ISSUE THREAD

**Issue by MaxiWaynee** [nSystemz/nemesus-world-server#6]
Wenn man zu mehrern leuten auf den server ist dann kommt es sehr oft vor das wenn einer zb. auf ein auto haut oder ein tier oder so erschießt das dann ein spieler einfach stirbt

**Comment by nSystemz** [comment]
Der Fehler kann aktuell nicht nachvollzogen werden, es sich natürlich um einen Sync Bug handeln. Wenn noch Probleme damit bestehen, melde dich gerne auf Discord bei mir.
