### ISSUE TITLE
Kofferraum speichert nicht

### ISSUE THREAD

**Issue by MaxiWaynee** [nSystemz/nemesus-world-server#8]
Wie im Titel erwähnt speichert anscheinend nicht das was man in den Kofferraum liegt wenn der server abschmiert

**Comment by nSystemz** [comment]
Ich empfehle wenn man eine nahtlose Speicherung haben möchte, nach dem reinlegen/rausnehmen von einem Gegenstand aus dem Kofferraum/Mittelkonsole folgende Funktion aufzurufen:

`DealerShipController.SaveOneVehicleData(car);`

So wie es jetzt auch im GM nachgetragen wurde.
